__device__ void calculateGlobalValues(
        int i,
        int j,
        int currentIdx,
        int previousHorIdx,
        int previousVerIdx,
        int previousDiagIdx,
        char horizontalItem,
        char verticalItem,
        short* primary,
        short* substitution,
        short* horizontal,
        short* vertical,
        short* substitutionScores,
        int gapOpenPenalty,
        int gapExtendPenalty);

__device__ void globalSimilarityScores(
        int seqSize,
        int refSize,
        int seqRefOffset,
        int refMatrixSize,
        short* primary,
        short* substitution,
        short* horizontal,
        short* vertical,
        int seqIdx,
        int refIdx,
        int seqsMaxSize,
        int refsMaxSize,
        char* seqs,
        char* refs,
        int refsCount,
        float* similarityScores);
